name: Build Teamwork App
on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        
    steps:
      - name: checkout git repository
        uses: actions/checkout@v3
        
      - name: Install Node,js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16"

      - name: Install yarn
        run: npm i -g yarn
      
      - name: Install Dependencies
        run: yarn