name: Build Teamwork App
on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        
    steps:
      - name: checkout git repository
        uses: actions/checkout@v3
        
      - name: Install Node,js
        uses: actions/setup-node@v3.0.0
        with:
          node-version: "16"

      - name: Install yarn
        run: npm i -g yarn
      
      - name: Install Dependencies
        run: yarn

      - name: Build for MacOs
        if: matrix.os == 'macos-latest'
        run: yarn build:mac

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: yarn build:linux

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: yarn build:win
      
      - name: release
        uses: softprops/action-gh-release@v0.1.14
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "dist/**"
